version: '3'

tasks:
  download:
    desc: Download Twickets APK
    dir: apk
    cmds:
      - uvx gplaydl auth
      - uvx gplaydl download co.twickets.droid --no-splits --no-extras
      - mv co.twickets.droid-*.apk twickets.apk

  decompile:
    desc: Decompile Twickets APK
    cmd: jadx -d decompiled apk/twickets.apk || true

  extract:
    desc: Extract API details
    cmds:
      - uv run scripts/extract.py decompiled
