version: '3'

tasks:
  decompile:
    desc: Decompile twickets apk
    cmd: jadx -d decompiled apk/twickets.apk

  extract:
    desc: Extract api details
    cmds:
      - python3 scripts/scan.py decompiled
